# Basic configuration
language: java
dist: trusty
services:
  - docker
jdk: oraclejdk8
sudo: false

# Increase the size of the heap, use urlDependencies plugin from cache
before_script:
  - "echo $JAVA_OPTS"
  - "export JAVA_OPTS=-Xmx1024m"
  - "[ ! -d urlDependencies-plugin ] || {echo Using urlDependencies-plugin from cache}"
  - "[ -d urlDependencies-plugin ] || git clone https://github.com/gchq/urlDependencies-plugin.git"
  - "pushd urlDependencies-plugin"
  - "[ -d urlDependencies-plugin ] || ./gradlew clean build publishToMavenLocal"
  - "popd"
  - "git clone https://github.com/gchq/stroom-resources.git"
  - "pushd stroom-resources/dev-resources/compose"
  - "docker-compose -f hbase-kafka-mysql-stroom-zk.yml up -d"
  - "popd"

install: echo "skip 'gradle assemble' step to speed up build"

# We need to run shadowJar otherwise we won't be able to publish to DockerHub
script: ./gradlew -Pversion=$TRAVIS_TAG downloadUrlDependencies clean build shadowJar -x integrationTest

# TODO: reinstate image releases and GitHub releases

# Push to DockerHub. The username and password were added using the Travis CLI.
# The configuration below will only push an image if the branch being built is master.
#after_success:
#  - docker build --tag=gchq/stroom:latest stroom-app/.
#  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
#  - if [ "$TRAVIS_BRANCH" == "master" ]; then
#    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
#    docker push gchq/stroom;
#    fi

# Push to GitHub releases - the key was generated by the Travis CLI.
deploy:
  provider: releases
  api_key:
    secure: wZBk0Md9y+04GNxcY5B8m/nIKNLRu+an0cKmxMGNkR1bBMcoQrpBUHBLR8rQd/FRfbjym25z8Q8+e3AunCFSHVvMPkvpBJsDhwl7H/4x3cZcdsjzOCAEPxKpk64SyG8GbR4r4Ue57lHeXKO2eTe4pfOn07yvkFQWr+Fll2qrgGKKk46VHc4LkYSycfLL6GaSS3wdggcVEzDfuXqF6agMfs3uCGsdOtHi+UHFZYSmstgG9kihDvKro1576aOhlIxZc+dQullFXGrOIpv+xKEyrsX86OQbAolsDkK/VgqDcZ7FiiD3XKMrPiPUIZFX7WoQO9ZjumHjGa0GyIxZnmF31sBcZi5LNaLvE6VacMU2C/HYS1TtkAXODX6Npz1I0vXj4uj/NjnABePtZOaGjIfxQ2N/YuyHan+1k1Mo+YA450Pd5hwMOEp1CYRpX8c9e8eUOq2l9I2je0uJwpE35pxBryXQpRtvrmqYbMAyy5KgqwMETKqrzcGDxhmik9u9eq29nesbTA/e6LLwcSw6WCIi/VoeV/D1prPWv02OHMaUGd4uEQP7mD6ijV8AA0P09FnhbS654gBHlOll745GrD52TaNt0k/LQJjI4lIhtJq0A19TAe7f0b2F2CvpXKJSyONWgbVeWgI6JjQi+dJ3vUeiMz1VbHFW3ImU=
  file_glob: true
  file: 
    - stroom-stats-service/build/libs/*-all.jar
    - stroom-stats-hbase-filter/build/libs/*-all.jar
    - stroom-stats-api/build/libs/*.jar
  skip_cleanup: true
  on:
    tags: true

#clean out gradle caches as per travis docs
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

# Cache dependencies to speed up the build
cache:
  directories:
    - .autoconf
    - $HOME/.m2
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - urlDependencies-plugin
