# Basic configuration
language: java
dist: trusty
services:
  - docker
jdk: oraclejdk8
sudo: false

# Increase the size of the heap, use urlDependencies plugin from cache
before_script:
  - "echo $JAVA_OPTS"
  - "export JAVA_OPTS=-Xmx1024m"
  - "git clone https://github.com/gchq/urlDependencies-plugin.git"
  - "pushd urlDependencies-plugin"
  - "./gradlew clean build publishToMavenLocal"
  - "popd"
  - "git clone https://github.com/gchq/stroom-resources.git"
  - "pushd stroom-resources/dev-resources/compose"
  #- "docker-compose -f hbase-kafka-mysql-stroom-zk.yml up -d"
  - "popd"

install: echo "skip 'gradle assemble' step to speed up build"

# We need to run shadowJar otherwise we won't be able to publish to DockerHub
script: ./gradlew -Pversion=$TRAVIS_TAG downloadUrlDependencies clean build shadowJar -x integrationTest

# TODO: reinstate image releases and GitHub releases

# Push to DockerHub. The username and password were added using the Travis CLI.
# The configuration below will only push an image if the branch being built is master.
#after_success:
#  - docker build --tag=gchq/stroom:latest stroom-app/.
#  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
#  - if [ "$TRAVIS_BRANCH" == "master" ]; then
#    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
#    docker push gchq/stroom;
#    fi

after_success:
  - ls -l stroom-stats-service/build/libs/*-all.jar
  - ls -l stroom-stats-hbase-filter/build/libs/*-all.jar
  - ls -l stroom-stats-api/build/libs/*.jar

# Push to GitHub releases - the key was generated by the Travis CLI.
deploy:
  provider: releases
  api_key:
    secure: aDEYP6/O0zYQKPND9fVwpwgB32fS2K9ImJSqUdRzgCnkC7jYHxnG/KZUs/Zs9F/D/GblpahreUH/zuw3iOwE5w8df/rFMPyx0Mr0bhO0e7yQAElpLYl5Xk5T+iwTdZcgUQb64rPnAg0axgic3mlXzJN19tB2NjTK+qsKmBhOqRdwv/R23hJlq+0+4z4vTJgRRbqLAJ6zz8aziZoGzPz87VrXGIUiP6pziHVopnnIAF2LAtOl0s3g5GuWYicdI9510DXB1BSA+NjeSk79BP2Tot/vLuHcdVWooDQuU2ABaFwMhCuOlmRARKUkC4VCPbA2XqhtmpfS5e4w5oMFxif35C+lPWgcG5ERTlSR9PQtuqE30hW4RhQTIw9YKYcmeh5jIRZVPPPeUs4bzEfN5qjFYjEs5Uf2DS6OqLOjbLHsfjfMqXUBgb11OJNxziIbnZqhE9fNsjMXGF2S1BG0rJWVno+AUun7HNZRGp0R+2z37eNXtoOMxX6FCbmjgxWJfzlBihsS4tzIUBPwHZ6XjL5O5bIqwb2PCFevmTkHHj3nBMi6gDFjgOCE0TmNdlWGqVYqGBEbnnC4idMaT8guWopCfK8VJ447jSKEA+bP/zrO5dcDTD9LQ+Ib6BUM5F8gJusEowX/ex+ngE+d0iAT6MIcydS5Ki1Of3x3dKc5txMDNTc=
  file_glob: true
  file: 
    - stroom-stats-service/build/libs/*-all.jar
    - stroom-stats-hbase-filter/build/libs/*-all.jar
    - stroom-stats-api/build/libs/*.jar
  skip_cleanup: true
  on:
    tags: true

#clean out gradle caches as per travis docs
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

# Cache dependencies to speed up the build
cache:
  directories:
    - .autoconf
    - $HOME/.m2
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
