# Basic configuration
language: java
dist: trusty
group: edge
jdk: openjdk8
#this is needed for using the docker daemon
sudo: required

env:
  global:
    # $TAGPERM environment variable
    # generate a token at https://github.com/settings/tokens and encrypt it
    # with `travis encrypt TAGPERM=<yoursecrettoken>`
    # also see: https://docs.travis-ci.com/user/encryption-keys/#Usage
    # and: https://docs.travis-ci.com/user/best-practices-security/
    - secure: "eEYzUNi44hdz7dfoLaJrajAEQNVqFoOnuBQvsUJkQlIciQp+69wJ4dFZOzsOrcDILwU11s05YbSqkQ3zGqkQfIRlwO45yHLvmjgPyk3DUxgF3fJytlCBxU90iZKQNBfhbgooXbpYpHLv6OHxU9JYQLeVY6LiY+4POPzfDqOIvCqFaJHNkM54TUtVMWI4lGHN1pNco98vlnrXOscyVLre8Of6X7skGlKt5v8im777wgaTQiF04HawUFSdUfEIBkSMyE76TCS9ifeNvg9ro6XwTZiiMfchavdPTQtj8+VvSoCIghuPdx7nGENuEKtwqwPHKdjNMA1ApX5wG8M2/sQG3ZmIorXk+oj/27RO7LkEcV3A9Uu1XqQAWE79PlHQQzuPZ9YNBuN5zYtOeHhqvpDkd48XjD79IZB7TqC8yI8Pzx6TV+1PVqfF3nncsUcv+2/HN5jjLMiogqynI//Mb2mrb5QZsZmxEZpi6P+tKuFNmm7+TyDYBRkT1YgEvW4Mzjemp0PufzdBr4Yo/ATOhfZw+xFhjeo6dWrb6+0qDcZB5aNVNB8LR48Hox/VCQJh4Eic59J7GEnqfDv1cX5/lwClJW1HrFPlptVm7EHRXZgw9cA1VNNGvG8qDERRjk1Jd/3cv/Sh3Pyfc5joNOjmKWiPNCoUciRcaz0cYLBjuznNq3c=" 

install: echo "skip 'gradle assemble' step to speed up build"

before_script: ./travis.before_script.sh

# We need to run shadowJar otherwise we won't be able to publish to DockerHub
script: ./travis.script.sh

# Push to GitHub releases - the key was generated by the Travis CLI.
deploy:
  provider: releases
  api_key:
      # travis encrypt -r gchq/stroom-stats <github personal access token>
    secure: W7Sliln+oRb04oPX7k19BdP4BFVIJ41MaSYYceOrYO6O6Lml8SEP/FPycQN113pjmOU8yOf2662VfjWpyd3MdG4RtbiNkuywQ4OSOEK8FftLIUGk+RdZ7DokUn5r+6paXJMNrR6uVcaGFsTCYLnpkI65UZBB/ZQPbwaUMT+ZIlxqy3Sm00pEAOA1ahgIWS37t3zeDse3Hm51tAvPfN+Ha4ibJDrRCgJFHJCQUjWysM+NQEUC91tdJc0/ZWWHDbVopcHnr340bxTnf6as4vvtRld/xB8VsUFqor7yB2ehu9H6PoNqTWjHoVjNUNPJSMUgtH5MtsJg1LwIy5sK2O689b2p7z2hJhtFPQySshf4eea61OCH6jYaWYcgpkEtsyQOPNLm5BVjDVmu6KNXPiLD9tu60LHx44Q2MXtClAtShCU9bWp8YsQFeQMt3jEPa1bQrywYajbZzNC9d93Jda2ftUWoEsjmiHfijsYpmbaF3PCu6mxy4hVIJyowlSF5qyu12EL7kxWRHSEco11C5dnVi/gobF8sgONHc/dPw3HM669a3ejRltEF0jJCbrId4bJvy6CuBdj0fz/VJbsqLth0Iuqn1Dg0uvwW7SFtXVcGKKsid/gXX8ZBqWorfnwh2EhBrI6RhNKUxZ2ydEvgPDARAosDAdq6TnUyNNhSwrJ7SE0=
  file_glob: true
  file: 
    - stroom-stats-service/build/libs/*-all.jar
    - stroom-stats-hbase-filter/build/libs/*-all.jar
    - stroom-stats-schema/build/libs/*.jar
  skip_cleanup: true
  on:
    tags: true

#clean out gradle caches as per travis docs
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

# Cache dependencies to speed up the build
cache:
  directories:
    - .autoconf
    - $HOME/.m2
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
