/*
 * Stroom Stats API
 * APIs for interacting with Stroom Stats.
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package stroom.stats.api.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import stroom.stats.api.model.TimeZone;

/**
 * The string formatting to apply to a date value
 */
@ApiModel(description = "The string formatting to apply to a date value")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-12-19T09:26:40.688Z")
public class DateTimeFormat {
  @SerializedName("pattern")
  private String pattern = null;

  @SerializedName("timeZone")
  private TimeZone timeZone = null;

  public DateTimeFormat pattern(String pattern) {
    this.pattern = pattern;
    return this;
  }

   /**
   * A date time formatting pattern string conforming to the specification of java.time.format.DateTimeFormatter
   * @return pattern
  **/
  @ApiModelProperty(example = "null", required = true, value = "A date time formatting pattern string conforming to the specification of java.time.format.DateTimeFormatter")
  public String getPattern() {
    return pattern;
  }

  public void setPattern(String pattern) {
    this.pattern = pattern;
  }

  public DateTimeFormat timeZone(TimeZone timeZone) {
    this.timeZone = timeZone;
    return this;
  }

   /**
   * Get timeZone
   * @return timeZone
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public TimeZone getTimeZone() {
    return timeZone;
  }

  public void setTimeZone(TimeZone timeZone) {
    this.timeZone = timeZone;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DateTimeFormat dateTimeFormat = (DateTimeFormat) o;
    return Objects.equals(this.pattern, dateTimeFormat.pattern) &&
        Objects.equals(this.timeZone, dateTimeFormat.timeZone);
  }

  @Override
  public int hashCode() {
    return Objects.hash(pattern, timeZone);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DateTimeFormat {\n");
    
    sb.append("    pattern: ").append(toIndentedString(pattern)).append("\n");
    sb.append("    timeZone: ").append(toIndentedString(timeZone)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

