/*
 * Stroom Stats API
 * APIs for interacting with Stroom Stats.
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package stroom.stats.api.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import stroom.stats.api.model.Field;
import stroom.stats.api.model.Result;

/**
 * FlatResult
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-12-19T09:26:40.688Z")
public class FlatResult extends Result {
  @SerializedName("structure")
  private List<Field> structure = new ArrayList<Field>();

  @SerializedName("values")
  private List<List<Object>> values = new ArrayList<List<Object>>();

  @SerializedName("size")
  private Long size = null;

  public FlatResult structure(List<Field> structure) {
    this.structure = structure;
    return this;
  }

  public FlatResult addStructureItem(Field structureItem) {
    this.structure.add(structureItem);
    return this;
  }

   /**
   * Get structure
   * @return structure
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<Field> getStructure() {
    return structure;
  }

  public void setStructure(List<Field> structure) {
    this.structure = structure;
  }

  public FlatResult values(List<List<Object>> values) {
    this.values = values;
    return this;
  }

  public FlatResult addValuesItem(List<Object> valuesItem) {
    this.values.add(valuesItem);
    return this;
  }

   /**
   * The 2 dimensional array containing the result set. The positions in the inner array correspond to the positions in the 'structure' property
   * @return values
  **/
  @ApiModelProperty(example = "null", value = "The 2 dimensional array containing the result set. The positions in the inner array correspond to the positions in the 'structure' property")
  public List<List<Object>> getValues() {
    return values;
  }

  public void setValues(List<List<Object>> values) {
    this.values = values;
  }

  public FlatResult size(Long size) {
    this.size = size;
    return this;
  }

   /**
   * The size of the result set being returned
   * @return size
  **/
  @ApiModelProperty(example = "null", value = "The size of the result set being returned")
  public Long getSize() {
    return size;
  }

  public void setSize(Long size) {
    this.size = size;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FlatResult flatResult = (FlatResult) o;
    return Objects.equals(this.structure, flatResult.structure) &&
        Objects.equals(this.values, flatResult.values) &&
        Objects.equals(this.size, flatResult.size) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(structure, values, size, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FlatResult {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    structure: ").append(toIndentedString(structure)).append("\n");
    sb.append("    values: ").append(toIndentedString(values)).append("\n");
    sb.append("    size: ").append(toIndentedString(size)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

