/*
 * Stroom Stats API
 * APIs for interacting with Stroom Stats.
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package stroom.stats.api.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * The offset and length of a range of data in a sub-set of a query result set
 */
@ApiModel(description = "The offset and length of a range of data in a sub-set of a query result set")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-12-19T09:26:40.688Z")
public class OffsetRange {
  @SerializedName("offset")
  private Long offset = null;

  @SerializedName("length")
  private Long length = null;

  public OffsetRange offset(Long offset) {
    this.offset = offset;
    return this;
  }

   /**
   * The start offset for this sub-set of data, where zero is the offset of the first record in the full result set
   * @return offset
  **/
  @ApiModelProperty(example = "0", required = true, value = "The start offset for this sub-set of data, where zero is the offset of the first record in the full result set")
  public Long getOffset() {
    return offset;
  }

  public void setOffset(Long offset) {
    this.offset = offset;
  }

  public OffsetRange length(Long length) {
    this.length = length;
    return this;
  }

   /**
   * The length in records of the sub-set of results
   * @return length
  **/
  @ApiModelProperty(example = "100", required = true, value = "The length in records of the sub-set of results")
  public Long getLength() {
    return length;
  }

  public void setLength(Long length) {
    this.length = length;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OffsetRange offsetRange = (OffsetRange) o;
    return Objects.equals(this.offset, offsetRange.offset) &&
        Objects.equals(this.length, offsetRange.length);
  }

  @Override
  public int hashCode() {
    return Objects.hash(offset, length);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OffsetRange {\n");
    
    sb.append("    offset: ").append(toIndentedString(offset)).append("\n");
    sb.append("    length: ").append(toIndentedString(length)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

