/*
 * Stroom Stats API
 * APIs for interacting with Stroom Stats.
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package stroom.stats.api.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import stroom.stats.api.model.DocRef;
import stroom.stats.api.model.ExpressionOperator;
import stroom.stats.api.model.Param;

/**
 * The query terms for the search
 */
@ApiModel(description = "The query terms for the search")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-12-19T13:37:48.590Z")
public class Query {
  @SerializedName("dataSource")
  private DocRef dataSource = null;

  @SerializedName("expression")
  private ExpressionOperator expression = null;

  @SerializedName("params")
  private List<Param> params = new ArrayList<Param>();

  public Query dataSource(DocRef dataSource) {
    this.dataSource = dataSource;
    return this;
  }

   /**
   * Get dataSource
   * @return dataSource
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public DocRef getDataSource() {
    return dataSource;
  }

  public void setDataSource(DocRef dataSource) {
    this.dataSource = dataSource;
  }

  public Query expression(ExpressionOperator expression) {
    this.expression = expression;
    return this;
  }

   /**
   * The root logical operator in the query expression tree
   * @return expression
  **/
  @ApiModelProperty(example = "null", required = true, value = "The root logical operator in the query expression tree")
  public ExpressionOperator getExpression() {
    return expression;
  }

  public void setExpression(ExpressionOperator expression) {
    this.expression = expression;
  }

  public Query params(List<Param> params) {
    this.params = params;
    return this;
  }

  public Query addParamsItem(Param paramsItem) {
    this.params.add(paramsItem);
    return this;
  }

   /**
   * A list of key/value pairs that provide additional information about the query
   * @return params
  **/
  @ApiModelProperty(example = "null", value = "A list of key/value pairs that provide additional information about the query")
  public List<Param> getParams() {
    return params;
  }

  public void setParams(List<Param> params) {
    this.params = params;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Query query = (Query) o;
    return Objects.equals(this.dataSource, query.dataSource) &&
        Objects.equals(this.expression, query.expression) &&
        Objects.equals(this.params, query.params);
  }

  @Override
  public int hashCode() {
    return Objects.hash(dataSource, expression, params);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Query {\n");
    
    sb.append("    dataSource: ").append(toIndentedString(dataSource)).append("\n");
    sb.append("    expression: ").append(toIndentedString(expression)).append("\n");
    sb.append("    params: ").append(toIndentedString(params)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

