/*
 * Stroom Stats API
 * APIs for interacting with Stroom Stats.
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package stroom.stats.api.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;

/**
 * A row of data in a result set
 */
@ApiModel(description = "A row of data in a result set")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-12-19T13:37:48.590Z")
public class Row {
  @SerializedName("groupKey")
  private String groupKey = null;

  @SerializedName("values")
  private List<String> values = new ArrayList<String>();

  @SerializedName("depth")
  private Integer depth = null;

  public Row groupKey(String groupKey) {
    this.groupKey = groupKey;
    return this;
  }

   /**
   * TODO
   * @return groupKey
  **/
  @ApiModelProperty(example = "null", required = true, value = "TODO")
  public String getGroupKey() {
    return groupKey;
  }

  public void setGroupKey(String groupKey) {
    this.groupKey = groupKey;
  }

  public Row values(List<String> values) {
    this.values = values;
    return this;
  }

  public Row addValuesItem(String valuesItem) {
    this.values.add(valuesItem);
    return this;
  }

   /**
   * The value for this row of data. The values in the list are in the same order as the fields in the ResultRequest
   * @return values
  **/
  @ApiModelProperty(example = "null", required = true, value = "The value for this row of data. The values in the list are in the same order as the fields in the ResultRequest")
  public List<String> getValues() {
    return values;
  }

  public void setValues(List<String> values) {
    this.values = values;
  }

  public Row depth(Integer depth) {
    this.depth = depth;
    return this;
  }

   /**
   * The grouping depth, where 0 is the top level of grouping, or where there is no grouping
   * @return depth
  **/
  @ApiModelProperty(example = "0", required = true, value = "The grouping depth, where 0 is the top level of grouping, or where there is no grouping")
  public Integer getDepth() {
    return depth;
  }

  public void setDepth(Integer depth) {
    this.depth = depth;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Row row = (Row) o;
    return Objects.equals(this.groupKey, row.groupKey) &&
        Objects.equals(this.values, row.values) &&
        Objects.equals(this.depth, row.depth);
  }

  @Override
  public int hashCode() {
    return Objects.hash(groupKey, values, depth);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Row {\n");
    
    sb.append("    groupKey: ").append(toIndentedString(groupKey)).append("\n");
    sb.append("    values: ").append(toIndentedString(values)).append("\n");
    sb.append("    depth: ").append(toIndentedString(depth)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

