/*
 * Stroom Stats API
 * APIs for interacting with Stroom Stats.
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package stroom.stats.api.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import stroom.stats.api.model.Query;
import stroom.stats.api.model.QueryKey;
import stroom.stats.api.model.ResultRequest;

/**
 * A request for new search or a follow up request for more data for an existing iterative search
 */
@ApiModel(description = "A request for new search or a follow up request for more data for an existing iterative search")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-12-19T13:37:48.590Z")
public class SearchRequest {
  @SerializedName("key")
  private QueryKey key = null;

  @SerializedName("query")
  private Query query = null;

  @SerializedName("resultRequests")
  private List<ResultRequest> resultRequests = new ArrayList<ResultRequest>();

  @SerializedName("dateTimeLocale")
  private String dateTimeLocale = null;

  @SerializedName("incremental")
  private Boolean incremental = null;

  public SearchRequest key(QueryKey key) {
    this.key = key;
    return this;
  }

   /**
   * Get key
   * @return key
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public QueryKey getKey() {
    return key;
  }

  public void setKey(QueryKey key) {
    this.key = key;
  }

  public SearchRequest query(Query query) {
    this.query = query;
    return this;
  }

   /**
   * Get query
   * @return query
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public Query getQuery() {
    return query;
  }

  public void setQuery(Query query) {
    this.query = query;
  }

  public SearchRequest resultRequests(List<ResultRequest> resultRequests) {
    this.resultRequests = resultRequests;
    return this;
  }

  public SearchRequest addResultRequestsItem(ResultRequest resultRequestsItem) {
    this.resultRequests.add(resultRequestsItem);
    return this;
  }

   /**
   * Get resultRequests
   * @return resultRequests
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public List<ResultRequest> getResultRequests() {
    return resultRequests;
  }

  public void setResultRequests(List<ResultRequest> resultRequests) {
    this.resultRequests = resultRequests;
  }

  public SearchRequest dateTimeLocale(String dateTimeLocale) {
    this.dateTimeLocale = dateTimeLocale;
    return this;
  }

   /**
   * The locale to use when formatting date values in the search results. The value is the string form of a java.time.ZoneId
   * @return dateTimeLocale
  **/
  @ApiModelProperty(example = "null", required = true, value = "The locale to use when formatting date values in the search results. The value is the string form of a java.time.ZoneId")
  public String getDateTimeLocale() {
    return dateTimeLocale;
  }

  public void setDateTimeLocale(String dateTimeLocale) {
    this.dateTimeLocale = dateTimeLocale;
  }

  public SearchRequest incremental(Boolean incremental) {
    this.incremental = incremental;
    return this;
  }

   /**
   * If true the response will contain all results found so far. Future requests for the same query key may return more results. Intended for use on longer running searches to allow partial result sets to be returned as soon as they are available rather than waiting for the full result set.
   * @return incremental
  **/
  @ApiModelProperty(example = "null", required = true, value = "If true the response will contain all results found so far. Future requests for the same query key may return more results. Intended for use on longer running searches to allow partial result sets to be returned as soon as they are available rather than waiting for the full result set.")
  public Boolean getIncremental() {
    return incremental;
  }

  public void setIncremental(Boolean incremental) {
    this.incremental = incremental;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SearchRequest searchRequest = (SearchRequest) o;
    return Objects.equals(this.key, searchRequest.key) &&
        Objects.equals(this.query, searchRequest.query) &&
        Objects.equals(this.resultRequests, searchRequest.resultRequests) &&
        Objects.equals(this.dateTimeLocale, searchRequest.dateTimeLocale) &&
        Objects.equals(this.incremental, searchRequest.incremental);
  }

  @Override
  public int hashCode() {
    return Objects.hash(key, query, resultRequests, dateTimeLocale, incremental);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SearchRequest {\n");
    
    sb.append("    key: ").append(toIndentedString(key)).append("\n");
    sb.append("    query: ").append(toIndentedString(query)).append("\n");
    sb.append("    resultRequests: ").append(toIndentedString(resultRequests)).append("\n");
    sb.append("    dateTimeLocale: ").append(toIndentedString(dateTimeLocale)).append("\n");
    sb.append("    incremental: ").append(toIndentedString(incremental)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

