/*
 * Stroom Stats API
 * APIs for interacting with Stroom Stats.
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package stroom.stats.api.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import stroom.stats.api.model.Result;

/**
 * The response to a search request, that may or may not contain results. The results may only be a partial set if an iterative screech was requested
 */
@ApiModel(description = "The response to a search request, that may or may not contain results. The results may only be a partial set if an iterative screech was requested")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-12-19T13:37:48.590Z")
public class SearchResponse {
  @SerializedName("highlights")
  private List<String> highlights = new ArrayList<String>();

  @SerializedName("results")
  private List<Result> results = new ArrayList<Result>();

  @SerializedName("errors")
  private List<String> errors = new ArrayList<String>();

  @SerializedName("complete")
  private Boolean complete = null;

  public SearchResponse highlights(List<String> highlights) {
    this.highlights = highlights;
    return this;
  }

  public SearchResponse addHighlightsItem(String highlightsItem) {
    this.highlights.add(highlightsItem);
    return this;
  }

   /**
   * A list of strings to highlight in the UI that should correlate with the search query.
   * @return highlights
  **/
  @ApiModelProperty(example = "null", required = true, value = "A list of strings to highlight in the UI that should correlate with the search query.")
  public List<String> getHighlights() {
    return highlights;
  }

  public void setHighlights(List<String> highlights) {
    this.highlights = highlights;
  }

  public SearchResponse results(List<Result> results) {
    this.results = results;
    return this;
  }

  public SearchResponse addResultsItem(Result resultsItem) {
    this.results.add(resultsItem);
    return this;
  }

   /**
   * Get results
   * @return results
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<Result> getResults() {
    return results;
  }

  public void setResults(List<Result> results) {
    this.results = results;
  }

  public SearchResponse errors(List<String> errors) {
    this.errors = errors;
    return this;
  }

  public SearchResponse addErrorsItem(String errorsItem) {
    this.errors.add(errorsItem);
    return this;
  }

   /**
   * A list of errors that occurred in running the query
   * @return errors
  **/
  @ApiModelProperty(example = "null", value = "A list of errors that occurred in running the query")
  public List<String> getErrors() {
    return errors;
  }

  public void setErrors(List<String> errors) {
    this.errors = errors;
  }

  public SearchResponse complete(Boolean complete) {
    this.complete = complete;
    return this;
  }

   /**
   * True if the query has returned all known results
   * @return complete
  **/
  @ApiModelProperty(example = "null", value = "True if the query has returned all known results")
  public Boolean getComplete() {
    return complete;
  }

  public void setComplete(Boolean complete) {
    this.complete = complete;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SearchResponse searchResponse = (SearchResponse) o;
    return Objects.equals(this.highlights, searchResponse.highlights) &&
        Objects.equals(this.results, searchResponse.results) &&
        Objects.equals(this.errors, searchResponse.errors) &&
        Objects.equals(this.complete, searchResponse.complete);
  }

  @Override
  public int hashCode() {
    return Objects.hash(highlights, results, errors, complete);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SearchResponse {\n");
    
    sb.append("    highlights: ").append(toIndentedString(highlights)).append("\n");
    sb.append("    results: ").append(toIndentedString(results)).append("\n");
    sb.append("    errors: ").append(toIndentedString(errors)).append("\n");
    sb.append("    complete: ").append(toIndentedString(complete)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

