/*
 * Stroom Stats API
 * APIs for interacting with Stroom Stats.
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package stroom.stats.api.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import stroom.stats.api.model.DocRef;
import stroom.stats.api.model.Field;

/**
 * An object to describe how the query results should be returned, including which fields should be included and what sorting, grouping, filtering, limiting, etc. should be applied
 */
@ApiModel(description = "An object to describe how the query results should be returned, including which fields should be included and what sorting, grouping, filtering, limiting, etc. should be applied")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-12-19T13:37:48.590Z")
public class TableSettings {
  @SerializedName("queryId")
  private String queryId = null;

  @SerializedName("fields")
  private List<Field> fields = new ArrayList<Field>();

  @SerializedName("extractValues")
  private Boolean extractValues = null;

  @SerializedName("extractionPipeline")
  private DocRef extractionPipeline = null;

  @SerializedName("maxResults")
  private List<Integer> maxResults = new ArrayList<Integer>();

  @SerializedName("showDetail")
  private Boolean showDetail = null;

  public TableSettings queryId(String queryId) {
    this.queryId = queryId;
    return this;
  }

   /**
   * TODO
   * @return queryId
  **/
  @ApiModelProperty(example = "null", required = true, value = "TODO")
  public String getQueryId() {
    return queryId;
  }

  public void setQueryId(String queryId) {
    this.queryId = queryId;
  }

  public TableSettings fields(List<Field> fields) {
    this.fields = fields;
    return this;
  }

  public TableSettings addFieldsItem(Field fieldsItem) {
    this.fields.add(fieldsItem);
    return this;
  }

   /**
   * Get fields
   * @return fields
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public List<Field> getFields() {
    return fields;
  }

  public void setFields(List<Field> fields) {
    this.fields = fields;
  }

  public TableSettings extractValues(Boolean extractValues) {
    this.extractValues = extractValues;
    return this;
  }

   /**
   * TODO
   * @return extractValues
  **/
  @ApiModelProperty(example = "null", value = "TODO")
  public Boolean getExtractValues() {
    return extractValues;
  }

  public void setExtractValues(Boolean extractValues) {
    this.extractValues = extractValues;
  }

  public TableSettings extractionPipeline(DocRef extractionPipeline) {
    this.extractionPipeline = extractionPipeline;
    return this;
  }

   /**
   * Get extractionPipeline
   * @return extractionPipeline
  **/
  @ApiModelProperty(example = "null", value = "")
  public DocRef getExtractionPipeline() {
    return extractionPipeline;
  }

  public void setExtractionPipeline(DocRef extractionPipeline) {
    this.extractionPipeline = extractionPipeline;
  }

  public TableSettings maxResults(List<Integer> maxResults) {
    this.maxResults = maxResults;
    return this;
  }

  public TableSettings addMaxResultsItem(Integer maxResultsItem) {
    this.maxResults.add(maxResultsItem);
    return this;
  }

   /**
   * Defines the maximum number of results to return at each grouping level, e.g. '1000,10,1' means 1000 results at group level 0, 10 at level 1 and 1 at level 2. In the absence of this field system defaults will apply
   * @return maxResults
  **/
  @ApiModelProperty(example = "&quot;1000,10,1&quot;", value = "Defines the maximum number of results to return at each grouping level, e.g. '1000,10,1' means 1000 results at group level 0, 10 at level 1 and 1 at level 2. In the absence of this field system defaults will apply")
  public List<Integer> getMaxResults() {
    return maxResults;
  }

  public void setMaxResults(List<Integer> maxResults) {
    this.maxResults = maxResults;
  }

  public TableSettings showDetail(Boolean showDetail) {
    this.showDetail = showDetail;
    return this;
  }

   /**
   * When grouping is used a value of true indicates that the results will include the full detail of any results aggregated into a group as well as their aggregates. A value of false will only include the aggregated values for each group. Defaults to false.
   * @return showDetail
  **/
  @ApiModelProperty(example = "null", value = "When grouping is used a value of true indicates that the results will include the full detail of any results aggregated into a group as well as their aggregates. A value of false will only include the aggregated values for each group. Defaults to false.")
  public Boolean getShowDetail() {
    return showDetail;
  }

  public void setShowDetail(Boolean showDetail) {
    this.showDetail = showDetail;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TableSettings tableSettings = (TableSettings) o;
    return Objects.equals(this.queryId, tableSettings.queryId) &&
        Objects.equals(this.fields, tableSettings.fields) &&
        Objects.equals(this.extractValues, tableSettings.extractValues) &&
        Objects.equals(this.extractionPipeline, tableSettings.extractionPipeline) &&
        Objects.equals(this.maxResults, tableSettings.maxResults) &&
        Objects.equals(this.showDetail, tableSettings.showDetail);
  }

  @Override
  public int hashCode() {
    return Objects.hash(queryId, fields, extractValues, extractionPipeline, maxResults, showDetail);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TableSettings {\n");
    
    sb.append("    queryId: ").append(toIndentedString(queryId)).append("\n");
    sb.append("    fields: ").append(toIndentedString(fields)).append("\n");
    sb.append("    extractValues: ").append(toIndentedString(extractValues)).append("\n");
    sb.append("    extractionPipeline: ").append(toIndentedString(extractionPipeline)).append("\n");
    sb.append("    maxResults: ").append(toIndentedString(maxResults)).append("\n");
    sb.append("    showDetail: ").append(toIndentedString(showDetail)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

