/*
 * Stroom Stats API
 * APIs for interacting with Stroom Stats.
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package stroom.stats.api.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import stroom.stats.api.model.OffsetRange;
import stroom.stats.api.model.Result;
import stroom.stats.api.model.Row;

/**
 * TableResult
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-12-19T09:26:40.688Z")
public class TableResult extends Result {
  @SerializedName("rows")
  private List<Row> rows = new ArrayList<Row>();

  @SerializedName("resultRange")
  private OffsetRange resultRange = null;

  @SerializedName("totalResults")
  private Integer totalResults = null;

  public TableResult rows(List<Row> rows) {
    this.rows = rows;
    return this;
  }

  public TableResult addRowsItem(Row rowsItem) {
    this.rows.add(rowsItem);
    return this;
  }

   /**
   * Get rows
   * @return rows
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public List<Row> getRows() {
    return rows;
  }

  public void setRows(List<Row> rows) {
    this.rows = rows;
  }

  public TableResult resultRange(OffsetRange resultRange) {
    this.resultRange = resultRange;
    return this;
  }

   /**
   * Get resultRange
   * @return resultRange
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public OffsetRange getResultRange() {
    return resultRange;
  }

  public void setResultRange(OffsetRange resultRange) {
    this.resultRange = resultRange;
  }

  public TableResult totalResults(Integer totalResults) {
    this.totalResults = totalResults;
    return this;
  }

   /**
   * The total number of results in this result set
   * @return totalResults
  **/
  @ApiModelProperty(example = "null", value = "The total number of results in this result set")
  public Integer getTotalResults() {
    return totalResults;
  }

  public void setTotalResults(Integer totalResults) {
    this.totalResults = totalResults;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TableResult tableResult = (TableResult) o;
    return Objects.equals(this.rows, tableResult.rows) &&
        Objects.equals(this.resultRange, tableResult.resultRange) &&
        Objects.equals(this.totalResults, tableResult.totalResults) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(rows, resultRange, totalResults, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TableResult {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    rows: ").append(toIndentedString(rows)).append("\n");
    sb.append("    resultRange: ").append(toIndentedString(resultRange)).append("\n");
    sb.append("    totalResults: ").append(toIndentedString(totalResults)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

