/*
 * Stroom Stats API
 * APIs for interacting with Stroom Stats.
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package stroom.stats.api.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * The timezone to apply to a date time value
 */
@ApiModel(description = "The timezone to apply to a date time value")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-12-19T13:37:48.590Z")
public class TimeZone {
  /**
   * The required type of time zone
   */
  public enum UseEnum {
    @SerializedName("LOCAL")
    LOCAL("LOCAL"),
    
    @SerializedName("UTC")
    UTC("UTC"),
    
    @SerializedName("ID")
    ID("ID"),
    
    @SerializedName("OFFSET")
    OFFSET("OFFSET");

    private String value;

    UseEnum(String value) {
      this.value = value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
  }

  @SerializedName("use")
  private UseEnum use = null;

  @SerializedName("id")
  private String id = null;

  @SerializedName("offsetHours")
  private Integer offsetHours = null;

  @SerializedName("offsetMinutes")
  private Integer offsetMinutes = null;

  public TimeZone use(UseEnum use) {
    this.use = use;
    return this;
  }

   /**
   * The required type of time zone
   * @return use
  **/
  @ApiModelProperty(example = "null", required = true, value = "The required type of time zone")
  public UseEnum getUse() {
    return use;
  }

  public void setUse(UseEnum use) {
    this.use = use;
  }

  public TimeZone id(String id) {
    this.id = id;
    return this;
  }

   /**
   * The id of the time zone, conforming to java.time.ZoneId
   * @return id
  **/
  @ApiModelProperty(example = "GMT", value = "The id of the time zone, conforming to java.time.ZoneId")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public TimeZone offsetHours(Integer offsetHours) {
    this.offsetHours = offsetHours;
    return this;
  }

   /**
   * The number of hours this timezone is offset from UTC
   * @return offsetHours
  **/
  @ApiModelProperty(example = "-1", value = "The number of hours this timezone is offset from UTC")
  public Integer getOffsetHours() {
    return offsetHours;
  }

  public void setOffsetHours(Integer offsetHours) {
    this.offsetHours = offsetHours;
  }

  public TimeZone offsetMinutes(Integer offsetMinutes) {
    this.offsetMinutes = offsetMinutes;
    return this;
  }

   /**
   * The number of minutes this timezone is offset from UTC
   * @return offsetMinutes
  **/
  @ApiModelProperty(example = "-30", value = "The number of minutes this timezone is offset from UTC")
  public Integer getOffsetMinutes() {
    return offsetMinutes;
  }

  public void setOffsetMinutes(Integer offsetMinutes) {
    this.offsetMinutes = offsetMinutes;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TimeZone timeZone = (TimeZone) o;
    return Objects.equals(this.use, timeZone.use) &&
        Objects.equals(this.id, timeZone.id) &&
        Objects.equals(this.offsetHours, timeZone.offsetHours) &&
        Objects.equals(this.offsetMinutes, timeZone.offsetMinutes);
  }

  @Override
  public int hashCode() {
    return Objects.hash(use, id, offsetHours, offsetMinutes);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TimeZone {\n");
    
    sb.append("    use: ").append(toIndentedString(use)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    offsetHours: ").append(toIndentedString(offsetHours)).append("\n");
    sb.append("    offsetMinutes: ").append(toIndentedString(offsetMinutes)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

