# Database settings.
database:
    # the name of the JDBC driver, mysql in our case
    driverClass: com.mysql.jdbc.Driver
    # the username
    user: stroomuser
    # the password
    password: stroompassword1
    # the JDBC URL; the database is called DWGettingStarted
    url: jdbc:mysql://localhost:3306/stroom?useUnicode=yes&characterEncoding=UTF-8

    properties:
        charSet: UTF-8
        hibernate.dialect: org.hibernate.dialect.MySQLInnoDBDialect
        #set to false for compatibility with stroom's legacy hibernate 4 configuration and schema
        hibernate.id.new_generator_mappings: false
        hibernate.show_sql: false

jwtTokenSecret: CHANGE_ME

server:
    adminMinThreads: 1
    adminMaxThreads: 10
    adminContextPath: /
    applicationContextPath: /
    applicationConnectors:
        - type: http
          port: 8085
    adminConnectors:
        - type: http
          port: 8086

logging:
    level: WARN
    loggers:
        org.hibernate.SQL: WARN
        stroom.stats: INFO
        io.dropwizard: INFO
#        stroom.stats.streams.StatisticsAggregationProcessor: TRACE
#        stroom.stats.streams.FullEndToEndIT: TRACE
#        stroom.stats.hbase.table.HBaseEventStoreTable: TRACE
        org.ehcache: INFO
        org.eclipse.jetty: INFO
    appenders:
      - type: console
        logFormat: "%-6level [%d{HH:mm:ss.SSS}] [%t] %logger{5} - %X{code} %msg %n"

zookeeper:
    # The quorum of zookeeper hosts to connect to
    # of the form host1:port1,host2:port2 etc.
    quorum: localhost:2181
    # The root path to use to chroot the zookeeper connection
    # All other paths are beneath this
    statsPath: /stroom-stats
    # The path for PropertyService content
    propertyServicePath: /propertyService
    # Timeout for waiting for initialisation of the property service tree cache
    propertyServiceTreeCacheTimeoutMs: 60000
    # The path to use for service discovery
    serviceDiscoveryPath: /stroom-services

kafka:
    groupId: stroom-service
    statisticsTopic: statistics
