# Database settings.
database:
    # the name of the JDBC driver, mysql in our case
    driverClass: com.mysql.jdbc.Driver
    # the username
    user: stroomuser
    # the password
    password: stroompassword1
    # the JDBC URL; the database is called DWGettingStarted
    url: jdbc:mysql://localhost:3306/stroom?useUnicode=yes&characterEncoding=UTF-8

    properties:
        charSet: UTF-8
        hibernate.dialect: org.hibernate.dialect.MySQLInnoDBDialect
        #set to false for compatibility with stroom's legacy hibernate 4 configuration and schema
        hibernate.id.new_generator_mappings: false

jwtTokenSecret: bd678197-a88e-499c-b03b-62c3dd7dfd2d

server:
    adminMinThreads: 1
    adminMaxThreads: 10
    adminContextPath: /admin
    applicationContextPath: /
    applicationConnectors:
        - type: http
          port: 8085
    adminConnectors:
        - type: http
          port: 8086

logging:
    level: WARN
    loggers:
        stroom.stats: INFO
#        stroom.stats.streams.FullEndToEndIT: TRACE
#        stroom.stats.hbase.table.HBaseEventStoreTable: TRACE
        org.ehcache: INFO
        org.eclipse.jetty: INFO

zookeeper:
    # The quorum of zookeeper hosts to connect to
    # of the form host1:port1,host2:port2 etc.
    quorum: localhost:2181
    # The root path to use to chroot the zookeeper connection
    # All other paths are beneath this
    rootPath: /stroom-stats
    # The path for PropertyService content
    propertyServicePath: /propertyService
    # Timeout for waiting for initialisation of the property service tree cache
    propertyServiceTreeCacheTimeoutMs: 60000

kafka:
    groupId: stroom-service
    statisticsTopic: statistics
